name: Ubuntu - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-20.04
    timeout-minutes: 9999
    
    steps:
      - name: Update and Install Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl python3 python3-pip
          
      - name: Download and Run Essentials
        run: |
          wget -O Downloads.sh "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.sh?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1"
          chmod +x Downloads.sh
          ./Downloads.sh

      - name: Log In To AnyDesk (if applicable)
        run: |
          # إذا كان لديك برنامج نصي للتسجيل في AnyDesk أو أي خدمة أخرى، يمكنك وضعه هنا
          # تأكد من أن يكون لديك البرنامج النصي المناسب وقم بإعداده للبيئة على Ubuntu
          echo "تسجيل الدخول إلى AnyDesk ليس مدعوماً على Ubuntu بشكل افتراضي"

      - name: Time Counter
        run: |
          python3 time.py
